<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.2 (Python 3.11.4 on darwin)" generated="2025-01-21T19:13:41.957306" rpa="false" schemaversion="5">
<suite id="s1" name="sampleTest" source="/Users/adarsh/Documents/CE/robot-selenium-example/sampleTest.robot">
<test id="s1-t1" name="BrowserStack Demo Website" line="5">
<errors>
<msg time="2025-01-21T19:13:41.988268" level="ERROR">Unexpected error: AttributeError: 'TestStatus' object has no attribute '_test'
Traceback (most recent call last):
  File "/Users/adarsh/Documents/CE/robot-selenium-example/env/lib/python3.11/site-packages/robot/utils/application.py", line 81, in _execute
    rc = self.main(arguments, **options)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adarsh/Documents/CE/robot-selenium-example/env/lib/python3.11/site-packages/robot/run.py", line 475, in main
    result = suite.run(settings)
             ^^^^^^^^^^^^^^^^^^^
  File "/Users/adarsh/Documents/CE/robot-selenium-example/env/lib/python3.11/site-packages/robot/running/model.py", line 802, in run
    self.visit(runner)
  File "/Users/adarsh/Documents/CE/robot-selenium-example/env/lib/python3.11/site-packages/robot/model/testsuite.py", line 421, in visit
    visitor.visit_suite(self)
  File "/Users/adarsh/Documents/CE/robot-selenium-example/env/lib/python3.11/site-packages/robot/model/visitor.py", line 132, in visit_suite
    suite.tests.visit(self)
  File "/Users/adarsh/Documents/CE/robot-selenium-example/env/lib/python3.11/site-packages/robot/model/itemlist.py", line 102, in visit
    item.visit(visitor)    # type: ignore
    ^^^^^^^^^^^^^^^^^^^
  File "/Users/adarsh/Documents/CE/robot-selenium-example/env/lib/python3.11/site-packages/robot/model/testcase.py", line 178, in visit
    visitor.visit_test(self)
  File "/Users/adarsh/Documents/CE/robot-selenium-example/env/lib/python3.11/site-packages/robot/running/suiterunner.py", line 144, in visit_test
    status = TestStatus(self.suite_status, result, settings.skip_on_failure,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/adarsh/Documents/CE/robot-selenium-example/env/lib/python3.11/site-packages/browserstack_sdk/__init__.py", line 1823, in bstack1l1lll1lll_opy_
    bstack111l11l1l_opy_ = self._test
                           ^^^^^^^^^^
AttributeError: 'TestStatus' object has no attribute '_test'</msg>
</errors>
</robot>
